// <auto-generated />
using System;
using HassCompanion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HassCompanion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523154310_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("HassCompanion.Models.Chore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreditsReward")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chores");
                });

            modelBuilder.Entity("HassCompanion.Models.ChoreSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rhythm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpecificDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeLabel")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimesPerWeek")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("DefaultPersonId");

                    b.ToTable("ChoreSchedules");
                });

            modelBuilder.Entity("HassCompanion.Models.ChoreTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClaimedByPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompletedByPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConfirmedByPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CreditsAwarded")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OccurrenceIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OccurrenceLabel")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("ClaimedByPersonId");

                    b.HasIndex("CompletedByPersonId");

                    b.HasIndex("ConfirmedByPersonId");

                    b.HasIndex("DefaultPersonId");

                    b.HasIndex("Status", "DueDate");

                    b.HasIndex("ScheduleId", "DueDate", "OccurrenceIndex")
                        .IsUnique();

                    b.ToTable("ChoreTasks");
                });

            modelBuilder.Entity("HassCompanion.Models.CreditTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChoreTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreTaskId");

                    b.HasIndex("PersonId", "Timestamp");

                    b.ToTable("CreditTransactions");
                });

            modelBuilder.Entity("HassCompanion.Models.InternetRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicableDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreditCostPerExtraMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DailyMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RuleType")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("WindowEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("WindowStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("InternetRules");
                });

            modelBuilder.Entity("HassCompanion.Models.MissedCreditsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditsNotEarned")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasPaused")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreTaskId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("PersonId", "Date");

                    b.ToTable("MissedCreditsLogs");
                });

            modelBuilder.Entity("HassCompanion.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceEntities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityPicture")
                        .HasColumnType("TEXT");

                    b.Property<string>("HaEntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HaTodoEntityId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HaEntityId")
                        .IsUnique();

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("HassCompanion.Models.ChoreSchedule", b =>
                {
                    b.HasOne("HassCompanion.Models.Chore", "Chore")
                        .WithMany("Schedules")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HassCompanion.Models.Person", "DefaultPerson")
                        .WithMany("DefaultSchedules")
                        .HasForeignKey("DefaultPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chore");

                    b.Navigation("DefaultPerson");
                });

            modelBuilder.Entity("HassCompanion.Models.ChoreTask", b =>
                {
                    b.HasOne("HassCompanion.Models.Chore", "Chore")
                        .WithMany("Tasks")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HassCompanion.Models.Person", "ClaimedByPerson")
                        .WithMany("ClaimedTasks")
                        .HasForeignKey("ClaimedByPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HassCompanion.Models.Person", "CompletedByPerson")
                        .WithMany()
                        .HasForeignKey("CompletedByPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HassCompanion.Models.Person", "ConfirmedByPerson")
                        .WithMany()
                        .HasForeignKey("ConfirmedByPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HassCompanion.Models.Person", "DefaultPerson")
                        .WithMany()
                        .HasForeignKey("DefaultPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HassCompanion.Models.ChoreSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chore");

                    b.Navigation("ClaimedByPerson");

                    b.Navigation("CompletedByPerson");

                    b.Navigation("ConfirmedByPerson");

                    b.Navigation("DefaultPerson");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("HassCompanion.Models.CreditTransaction", b =>
                {
                    b.HasOne("HassCompanion.Models.ChoreTask", "ChoreTask")
                        .WithMany()
                        .HasForeignKey("ChoreTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HassCompanion.Models.Person", "Person")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChoreTask");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HassCompanion.Models.InternetRule", b =>
                {
                    b.HasOne("HassCompanion.Models.Person", "Person")
                        .WithMany("InternetRules")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HassCompanion.Models.MissedCreditsLog", b =>
                {
                    b.HasOne("HassCompanion.Models.ChoreTask", "ChoreTask")
                        .WithMany()
                        .HasForeignKey("ChoreTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HassCompanion.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HassCompanion.Models.ChoreSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChoreTask");

                    b.Navigation("Person");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("HassCompanion.Models.Chore", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("HassCompanion.Models.Person", b =>
                {
                    b.Navigation("ClaimedTasks");

                    b.Navigation("CreditTransactions");

                    b.Navigation("DefaultSchedules");

                    b.Navigation("InternetRules");
                });
#pragma warning restore 612, 618
        }
    }
}
