// <auto-generated />
using System;
using FamilyAssistant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyAssistant.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527195643_AddPersonAchievement")]
    partial class AddPersonAchievement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("FamilyAssistant.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("FamilyAssistant.Models.Chore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreditsReward")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconColor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chores");
                });

            modelBuilder.Entity("FamilyAssistant.Models.ChoreSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IntervalMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IntervalWeeks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rhythm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpecificDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeLabel")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimesPerWeek")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("DefaultPersonId");

                    b.ToTable("ChoreSchedules");
                });

            modelBuilder.Entity("FamilyAssistant.Models.ChoreTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClaimedByPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompletedByPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConfirmedByPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CreditsAwarded")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OccurrenceIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OccurrenceLabel")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("ClaimedByPersonId");

                    b.HasIndex("CompletedByPersonId");

                    b.HasIndex("ConfirmedByPersonId");

                    b.HasIndex("DefaultPersonId");

                    b.HasIndex("Status", "DueDate");

                    b.HasIndex("ScheduleId", "DueDate", "OccurrenceIndex");

                    b.ToTable("ChoreTasks");
                });

            modelBuilder.Entity("FamilyAssistant.Models.CreditTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChoreTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreTaskId");

                    b.HasIndex("PersonId", "Timestamp");

                    b.ToTable("CreditTransactions");
                });

            modelBuilder.Entity("FamilyAssistant.Models.EventTrigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebounceMins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("EntityId");

                    b.ToTable("EventTriggers");
                });

            modelBuilder.Entity("FamilyAssistant.Models.InternetRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicableDays")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("BudgetResetTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditCostPerExtraMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DailyBudgetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DetectionThresholdMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GracePeriodMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotifyAtPercent")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RuleMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Target")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("WindowEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("WindowStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("InternetRules");
                });

            modelBuilder.Entity("FamilyAssistant.Models.MissedCreditsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditsNotEarned")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasPaused")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreTaskId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("PersonId", "Date");

                    b.ToTable("MissedCreditsLogs");
                });

            modelBuilder.Entity("FamilyAssistant.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityPicture")
                        .HasColumnType("TEXT");

                    b.Property<string>("HaEntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HaTodoEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HaUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotifyEntity")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HaEntityId")
                        .IsUnique();

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("FamilyAssistant.Models.PersonAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AchievementKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Revealed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "AchievementKey")
                        .IsUnique();

                    b.ToTable("PersonAchievements");
                });

            modelBuilder.Entity("FamilyAssistant.Models.PersonDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetectionEntity")
                        .HasColumnType("TEXT");

                    b.Property<string>("GamingBlockEntity")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternetSwitchEntity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("InvertGamingBlock")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InvertInternetSwitch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonDevices");
                });

            modelBuilder.Entity("FamilyAssistant.Models.TaskAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskCommentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaskCommentId");

                    b.ToTable("TaskAttachments");
                });

            modelBuilder.Entity("FamilyAssistant.Models.TaskComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ChoreTaskId", "CreatedAt");

                    b.ToTable("TaskComments");
                });

            modelBuilder.Entity("InternetRuleDevices", b =>
                {
                    b.Property<int>("AffectedDevicesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InternetRulesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AffectedDevicesId", "InternetRulesId");

                    b.HasIndex("InternetRulesId");

                    b.ToTable("InternetRuleDevices");
                });

            modelBuilder.Entity("FamilyAssistant.Models.ChoreSchedule", b =>
                {
                    b.HasOne("FamilyAssistant.Models.Chore", "Chore")
                        .WithMany("Schedules")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssistant.Models.Person", "DefaultPerson")
                        .WithMany("DefaultSchedules")
                        .HasForeignKey("DefaultPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chore");

                    b.Navigation("DefaultPerson");
                });

            modelBuilder.Entity("FamilyAssistant.Models.ChoreTask", b =>
                {
                    b.HasOne("FamilyAssistant.Models.Chore", "Chore")
                        .WithMany("Tasks")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssistant.Models.Person", "ClaimedByPerson")
                        .WithMany("ClaimedTasks")
                        .HasForeignKey("ClaimedByPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyAssistant.Models.Person", "CompletedByPerson")
                        .WithMany()
                        .HasForeignKey("CompletedByPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyAssistant.Models.Person", "ConfirmedByPerson")
                        .WithMany()
                        .HasForeignKey("ConfirmedByPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyAssistant.Models.Person", "DefaultPerson")
                        .WithMany()
                        .HasForeignKey("DefaultPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyAssistant.Models.ChoreSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Chore");

                    b.Navigation("ClaimedByPerson");

                    b.Navigation("CompletedByPerson");

                    b.Navigation("ConfirmedByPerson");

                    b.Navigation("DefaultPerson");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("FamilyAssistant.Models.CreditTransaction", b =>
                {
                    b.HasOne("FamilyAssistant.Models.ChoreTask", "ChoreTask")
                        .WithMany()
                        .HasForeignKey("ChoreTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyAssistant.Models.Person", "Person")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChoreTask");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FamilyAssistant.Models.EventTrigger", b =>
                {
                    b.HasOne("FamilyAssistant.Models.Chore", "Chore")
                        .WithMany()
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chore");
                });

            modelBuilder.Entity("FamilyAssistant.Models.InternetRule", b =>
                {
                    b.HasOne("FamilyAssistant.Models.Person", "Person")
                        .WithMany("InternetRules")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FamilyAssistant.Models.MissedCreditsLog", b =>
                {
                    b.HasOne("FamilyAssistant.Models.ChoreTask", "ChoreTask")
                        .WithMany()
                        .HasForeignKey("ChoreTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssistant.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssistant.Models.ChoreSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChoreTask");

                    b.Navigation("Person");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("FamilyAssistant.Models.PersonAchievement", b =>
                {
                    b.HasOne("FamilyAssistant.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FamilyAssistant.Models.PersonDevice", b =>
                {
                    b.HasOne("FamilyAssistant.Models.Person", "Person")
                        .WithMany("Devices")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FamilyAssistant.Models.TaskAttachment", b =>
                {
                    b.HasOne("FamilyAssistant.Models.TaskComment", "TaskComment")
                        .WithMany("Attachments")
                        .HasForeignKey("TaskCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskComment");
                });

            modelBuilder.Entity("FamilyAssistant.Models.TaskComment", b =>
                {
                    b.HasOne("FamilyAssistant.Models.ChoreTask", "ChoreTask")
                        .WithMany("Comments")
                        .HasForeignKey("ChoreTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssistant.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChoreTask");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("InternetRuleDevices", b =>
                {
                    b.HasOne("FamilyAssistant.Models.PersonDevice", null)
                        .WithMany()
                        .HasForeignKey("AffectedDevicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssistant.Models.InternetRule", null)
                        .WithMany()
                        .HasForeignKey("InternetRulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyAssistant.Models.Chore", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("FamilyAssistant.Models.ChoreTask", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("FamilyAssistant.Models.Person", b =>
                {
                    b.Navigation("ClaimedTasks");

                    b.Navigation("CreditTransactions");

                    b.Navigation("DefaultSchedules");

                    b.Navigation("Devices");

                    b.Navigation("InternetRules");
                });

            modelBuilder.Entity("FamilyAssistant.Models.TaskComment", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
