// <auto-generated />
using System;
using FamilyAssistant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyAssistant.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609202957_AddRecipeStepIngredientMarkup")]
    partial class AddRecipeStepIngredientMarkup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("FamilyAssistant.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("FamilyAssistant.Models.Chore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreditsReward")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconColor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chores");
                });

            modelBuilder.Entity("FamilyAssistant.Models.ChoreSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IntervalMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IntervalWeeks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rhythm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpecificDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeLabel")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimesPerWeek")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("DefaultPersonId");

                    b.ToTable("ChoreSchedules");
                });

            modelBuilder.Entity("FamilyAssistant.Models.ChoreTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClaimedByPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompletedByPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConfirmedByPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CreditsAwarded")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OccurrenceIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OccurrenceLabel")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("ClaimedByPersonId");

                    b.HasIndex("CompletedByPersonId");

                    b.HasIndex("ConfirmedByPersonId");

                    b.HasIndex("DefaultPersonId");

                    b.HasIndex("Status", "DueDate");

                    b.HasIndex("ScheduleId", "DueDate", "OccurrenceIndex");

                    b.ToTable("ChoreTasks");
                });

            modelBuilder.Entity("FamilyAssistant.Models.CreditTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChoreTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreTaskId");

                    b.HasIndex("PersonId", "Timestamp");

                    b.ToTable("CreditTransactions");
                });

            modelBuilder.Entity("FamilyAssistant.Models.EventTrigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebounceMins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("EntityId");

                    b.ToTable("EventTriggers");
                });

            modelBuilder.Entity("FamilyAssistant.Models.InternetRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicableDays")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("BudgetResetTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditCostPerExtraMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DailyBudgetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DetectionThresholdMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GracePeriodMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotifyAtPercent")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RuleMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Target")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("WindowEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("WindowStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("InternetRules");
                });

            modelBuilder.Entity("FamilyAssistant.Models.MissedCreditsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditsNotEarned")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasPaused")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreTaskId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("PersonId", "Date");

                    b.ToTable("MissedCreditsLogs");
                });

            modelBuilder.Entity("FamilyAssistant.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityPicture")
                        .HasColumnType("TEXT");

                    b.Property<string>("HaEntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HaTodoEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HaUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotifyEntity")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HaEntityId")
                        .IsUnique();

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("FamilyAssistant.Models.PersonAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AchievementKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Revealed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "AchievementKey")
                        .IsUnique();

                    b.ToTable("PersonAchievements");
                });

            modelBuilder.Entity("FamilyAssistant.Models.PersonDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetectionEntity")
                        .HasColumnType("TEXT");

                    b.Property<string>("GamingBlockEntity")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternetSwitchEntity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("InvertGamingBlock")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InvertInternetSwitch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonDevices");
                });

            modelBuilder.Entity("FamilyAssistant.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseServings")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CookTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RestTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceText")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId", "Name");

                    b.ToTable("RecipeCategories");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "CreatedAt");

                    b.ToTable("RecipeImages");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeImportCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HeartbeatAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PauseRequested")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgressMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProposalName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QualityReport")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceText")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeartbeatAt");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("RecipeImportCandidates");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeImportTraceEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId", "AttemptNumber", "SortOrder");

                    b.ToTable("RecipeImportTraceEntries");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarkerToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("RecipeId", "MarkerToken");

                    b.HasIndex("RecipeId", "SortOrder");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeIngredientGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "SortOrder");

                    b.ToTable("RecipeIngredientGroups");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructionMarkup")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "SortOrder");

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeStepImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeStepId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeStepId", "CreatedAt");

                    b.ToTable("RecipeStepImages");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeStepIngredient", b =>
                {
                    b.Property<int>("RecipeStepId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeIngredientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipeStepId", "RecipeIngredientId");

                    b.HasIndex("RecipeIngredientId");

                    b.ToTable("RecipeStepIngredients");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RecipeTags");
                });

            modelBuilder.Entity("FamilyAssistant.Models.TaskAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskCommentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaskCommentId");

                    b.ToTable("TaskAttachments");
                });

            modelBuilder.Entity("FamilyAssistant.Models.TaskComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ChoreTaskId", "CreatedAt");

                    b.ToTable("TaskComments");
                });

            modelBuilder.Entity("InternetRuleDevices", b =>
                {
                    b.Property<int>("AffectedDevicesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InternetRulesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AffectedDevicesId", "InternetRulesId");

                    b.HasIndex("InternetRulesId");

                    b.ToTable("InternetRuleDevices");
                });

            modelBuilder.Entity("RecipeRecipeTags", b =>
                {
                    b.Property<int>("RecipesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("RecipeRecipeTags");
                });

            modelBuilder.Entity("FamilyAssistant.Models.ChoreSchedule", b =>
                {
                    b.HasOne("FamilyAssistant.Models.Chore", "Chore")
                        .WithMany("Schedules")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssistant.Models.Person", "DefaultPerson")
                        .WithMany("DefaultSchedules")
                        .HasForeignKey("DefaultPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chore");

                    b.Navigation("DefaultPerson");
                });

            modelBuilder.Entity("FamilyAssistant.Models.ChoreTask", b =>
                {
                    b.HasOne("FamilyAssistant.Models.Chore", "Chore")
                        .WithMany("Tasks")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssistant.Models.Person", "ClaimedByPerson")
                        .WithMany("ClaimedTasks")
                        .HasForeignKey("ClaimedByPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyAssistant.Models.Person", "CompletedByPerson")
                        .WithMany()
                        .HasForeignKey("CompletedByPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyAssistant.Models.Person", "ConfirmedByPerson")
                        .WithMany()
                        .HasForeignKey("ConfirmedByPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyAssistant.Models.Person", "DefaultPerson")
                        .WithMany()
                        .HasForeignKey("DefaultPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyAssistant.Models.ChoreSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Chore");

                    b.Navigation("ClaimedByPerson");

                    b.Navigation("CompletedByPerson");

                    b.Navigation("ConfirmedByPerson");

                    b.Navigation("DefaultPerson");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("FamilyAssistant.Models.CreditTransaction", b =>
                {
                    b.HasOne("FamilyAssistant.Models.ChoreTask", "ChoreTask")
                        .WithMany()
                        .HasForeignKey("ChoreTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyAssistant.Models.Person", "Person")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChoreTask");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FamilyAssistant.Models.EventTrigger", b =>
                {
                    b.HasOne("FamilyAssistant.Models.Chore", "Chore")
                        .WithMany()
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chore");
                });

            modelBuilder.Entity("FamilyAssistant.Models.InternetRule", b =>
                {
                    b.HasOne("FamilyAssistant.Models.Person", "Person")
                        .WithMany("InternetRules")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FamilyAssistant.Models.MissedCreditsLog", b =>
                {
                    b.HasOne("FamilyAssistant.Models.ChoreTask", "ChoreTask")
                        .WithMany()
                        .HasForeignKey("ChoreTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssistant.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssistant.Models.ChoreSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChoreTask");

                    b.Navigation("Person");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("FamilyAssistant.Models.PersonAchievement", b =>
                {
                    b.HasOne("FamilyAssistant.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FamilyAssistant.Models.PersonDevice", b =>
                {
                    b.HasOne("FamilyAssistant.Models.Person", "Person")
                        .WithMany("Devices")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FamilyAssistant.Models.Recipe", b =>
                {
                    b.HasOne("FamilyAssistant.Models.RecipeCategory", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeCategory", b =>
                {
                    b.HasOne("FamilyAssistant.Models.RecipeCategory", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeImage", b =>
                {
                    b.HasOne("FamilyAssistant.Models.Recipe", "Recipe")
                        .WithMany("Images")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeImportTraceEntry", b =>
                {
                    b.HasOne("FamilyAssistant.Models.RecipeImportCandidate", "Candidate")
                        .WithMany("TraceEntries")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeIngredient", b =>
                {
                    b.HasOne("FamilyAssistant.Models.RecipeIngredientGroup", "Group")
                        .WithMany("Ingredients")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyAssistant.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeIngredientGroup", b =>
                {
                    b.HasOne("FamilyAssistant.Models.Recipe", "Recipe")
                        .WithMany("IngredientGroups")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeStep", b =>
                {
                    b.HasOne("FamilyAssistant.Models.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeStepImage", b =>
                {
                    b.HasOne("FamilyAssistant.Models.RecipeStep", "RecipeStep")
                        .WithMany("Images")
                        .HasForeignKey("RecipeStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipeStep");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeStepIngredient", b =>
                {
                    b.HasOne("FamilyAssistant.Models.RecipeIngredient", "RecipeIngredient")
                        .WithMany("StepLinks")
                        .HasForeignKey("RecipeIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssistant.Models.RecipeStep", "RecipeStep")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipeIngredient");

                    b.Navigation("RecipeStep");
                });

            modelBuilder.Entity("FamilyAssistant.Models.TaskAttachment", b =>
                {
                    b.HasOne("FamilyAssistant.Models.TaskComment", "TaskComment")
                        .WithMany("Attachments")
                        .HasForeignKey("TaskCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskComment");
                });

            modelBuilder.Entity("FamilyAssistant.Models.TaskComment", b =>
                {
                    b.HasOne("FamilyAssistant.Models.ChoreTask", "ChoreTask")
                        .WithMany("Comments")
                        .HasForeignKey("ChoreTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssistant.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChoreTask");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("InternetRuleDevices", b =>
                {
                    b.HasOne("FamilyAssistant.Models.PersonDevice", null)
                        .WithMany()
                        .HasForeignKey("AffectedDevicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssistant.Models.InternetRule", null)
                        .WithMany()
                        .HasForeignKey("InternetRulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeRecipeTags", b =>
                {
                    b.HasOne("FamilyAssistant.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssistant.Models.RecipeTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyAssistant.Models.Chore", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("FamilyAssistant.Models.ChoreTask", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("FamilyAssistant.Models.Person", b =>
                {
                    b.Navigation("ClaimedTasks");

                    b.Navigation("CreditTransactions");

                    b.Navigation("DefaultSchedules");

                    b.Navigation("Devices");

                    b.Navigation("InternetRules");
                });

            modelBuilder.Entity("FamilyAssistant.Models.Recipe", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("IngredientGroups");

                    b.Navigation("Ingredients");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeImportCandidate", b =>
                {
                    b.Navigation("TraceEntries");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeIngredient", b =>
                {
                    b.Navigation("StepLinks");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeIngredientGroup", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("FamilyAssistant.Models.RecipeStep", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("FamilyAssistant.Models.TaskComment", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
