// <auto-generated />
using System;
using FamilyAssist.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyAssist.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("FamilyAssist.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("FamilyAssist.Models.Chore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreditsReward")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconColor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chores");
                });

            modelBuilder.Entity("FamilyAssist.Models.ChoreSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IntervalMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IntervalWeeks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rhythm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpecificDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeLabel")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimesPerWeek")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("DefaultPersonId");

                    b.ToTable("ChoreSchedules");
                });

            modelBuilder.Entity("FamilyAssist.Models.ChoreTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClaimedByPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompletedByPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConfirmedByPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CreditsAwarded")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OccurrenceIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OccurrenceLabel")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("ClaimedByPersonId");

                    b.HasIndex("CompletedByPersonId");

                    b.HasIndex("ConfirmedByPersonId");

                    b.HasIndex("DefaultPersonId");

                    b.HasIndex("Status", "DueDate");

                    b.HasIndex("ScheduleId", "DueDate", "OccurrenceIndex");

                    b.ToTable("ChoreTasks");
                });

            modelBuilder.Entity("FamilyAssist.Models.CreditTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChoreTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreTaskId");

                    b.HasIndex("PersonId", "Timestamp");

                    b.ToTable("CreditTransactions");
                });

            modelBuilder.Entity("FamilyAssist.Models.EventTrigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebounceMins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("EntityId");

                    b.ToTable("EventTriggers");
                });

            modelBuilder.Entity("FamilyAssist.Models.InternetRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicableDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreditCostPerExtraMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DailyMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RuleType")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("WindowEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("WindowStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("InternetRules");
                });

            modelBuilder.Entity("FamilyAssist.Models.MissedCreditsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditsNotEarned")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasPaused")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreTaskId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("PersonId", "Date");

                    b.ToTable("MissedCreditsLogs");
                });

            modelBuilder.Entity("FamilyAssist.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceEntities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityPicture")
                        .HasColumnType("TEXT");

                    b.Property<string>("HaEntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HaTodoEntityId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HaEntityId")
                        .IsUnique();

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("FamilyAssist.Models.TaskAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskCommentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaskCommentId");

                    b.ToTable("TaskAttachments");
                });

            modelBuilder.Entity("FamilyAssist.Models.TaskComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ChoreTaskId", "CreatedAt");

                    b.ToTable("TaskComments");
                });

            modelBuilder.Entity("FamilyAssist.Models.ChoreSchedule", b =>
                {
                    b.HasOne("FamilyAssist.Models.Chore", "Chore")
                        .WithMany("Schedules")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssist.Models.Person", "DefaultPerson")
                        .WithMany("DefaultSchedules")
                        .HasForeignKey("DefaultPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chore");

                    b.Navigation("DefaultPerson");
                });

            modelBuilder.Entity("FamilyAssist.Models.ChoreTask", b =>
                {
                    b.HasOne("FamilyAssist.Models.Chore", "Chore")
                        .WithMany("Tasks")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssist.Models.Person", "ClaimedByPerson")
                        .WithMany("ClaimedTasks")
                        .HasForeignKey("ClaimedByPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyAssist.Models.Person", "CompletedByPerson")
                        .WithMany()
                        .HasForeignKey("CompletedByPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyAssist.Models.Person", "ConfirmedByPerson")
                        .WithMany()
                        .HasForeignKey("ConfirmedByPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyAssist.Models.Person", "DefaultPerson")
                        .WithMany()
                        .HasForeignKey("DefaultPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyAssist.Models.ChoreSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Chore");

                    b.Navigation("ClaimedByPerson");

                    b.Navigation("CompletedByPerson");

                    b.Navigation("ConfirmedByPerson");

                    b.Navigation("DefaultPerson");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("FamilyAssist.Models.CreditTransaction", b =>
                {
                    b.HasOne("FamilyAssist.Models.ChoreTask", "ChoreTask")
                        .WithMany()
                        .HasForeignKey("ChoreTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyAssist.Models.Person", "Person")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChoreTask");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FamilyAssist.Models.EventTrigger", b =>
                {
                    b.HasOne("FamilyAssist.Models.Chore", "Chore")
                        .WithMany()
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chore");
                });

            modelBuilder.Entity("FamilyAssist.Models.InternetRule", b =>
                {
                    b.HasOne("FamilyAssist.Models.Person", "Person")
                        .WithMany("InternetRules")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FamilyAssist.Models.MissedCreditsLog", b =>
                {
                    b.HasOne("FamilyAssist.Models.ChoreTask", "ChoreTask")
                        .WithMany()
                        .HasForeignKey("ChoreTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssist.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssist.Models.ChoreSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChoreTask");

                    b.Navigation("Person");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("FamilyAssist.Models.TaskAttachment", b =>
                {
                    b.HasOne("FamilyAssist.Models.TaskComment", "TaskComment")
                        .WithMany("Attachments")
                        .HasForeignKey("TaskCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskComment");
                });

            modelBuilder.Entity("FamilyAssist.Models.TaskComment", b =>
                {
                    b.HasOne("FamilyAssist.Models.ChoreTask", "ChoreTask")
                        .WithMany("Comments")
                        .HasForeignKey("ChoreTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAssist.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChoreTask");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FamilyAssist.Models.Chore", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("FamilyAssist.Models.ChoreTask", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("FamilyAssist.Models.Person", b =>
                {
                    b.Navigation("ClaimedTasks");

                    b.Navigation("CreditTransactions");

                    b.Navigation("DefaultSchedules");

                    b.Navigation("InternetRules");
                });

            modelBuilder.Entity("FamilyAssist.Models.TaskComment", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
